#!/usr/local/bin/python
import random
import linecache
import sys

word_l_file = "words-l-curated.txt"
word_o_file = "words-o-curated.txt"
word_m_file = "words-m-curated.txt"

if len(sys.argv) >= 2:
	num_acros = int(sys.argv[1])
else:
	num_acros = 1

for x in range(num_acros):

	l_file = open(word_l_file)
	l_len = 0
	for x in l_file:
	    l_len += 1

	o_file = open(word_o_file)
	o_len = 0
	for x in o_file:
	    o_len += 1

	m_file = open(word_m_file)
	m_len = 0
	for x in m_file:
	    m_len += 1

	l1 = random.randint(1, l_len)
	o1 = random.randint(1, o_len)
	o2 = random.randint(1, o_len)
	m1 = random.randint(1, m_len)

	l_word = linecache.getline(word_l_file, l1).rstrip()
	o_word1 = linecache.getline(word_o_file, o1).rstrip()
	o_word2 = linecache.getline(word_o_file, o2).rstrip()
	m_word = linecache.getline(word_m_file, m1).rstrip()

	loom_acro = [l_word, o_word1, o_word2, m_word]

	print ' '.join(loom_acro)